### ISSUE TITLE
Problema al modificar un catálogo con nombre válido al añadir un campo que comience con espacio.

### ISSUE THREAD

**Issue by J0hnG4lt** [SergioTeranZ/Sistemas2#5]
Edit: el campo testeado es de tipo texto.

<type 'exceptions.IndexError'> list index out of range

File "/home/ubuntu/workspace/web2py/applications/Sistemas2/controllers/catalogo.py", line 498, in vModificarCatalogo
    idd_campo = db(db.CAMPO_CATALOGO.nombre == request.vars.nombre).select(db.CAMPO_CATALOGO.id_campo_cat)[0].id_campo_cat

**Comment by leotms** [comment]
Creo que puede solucionarse si en vez de enviar el nombre del catalogo via la URL, se envia la ID del catalogo que se quiere modificar/eliminar. Probablemente mañana pueda probarlo.

**Comment by J0hnG4lt** [comment]
Se tomó en cuenta tu sugerencia en 09330a1cce78a8f083deff100394b5dc6fa8c006
