### ISSUE TITLE
Problema al eliminar un valor con caracteres no ASCII de un catálogo

### ISSUE THREAD

**Issue by J0hnG4lt** [SergioTeranZ/Sistemas2#7]
Dado un catálogo, si se elimina una fila que tenga como valor un string con caracteres no ASCII en su primera columna, ocurre un error. Para solucionar esto, es necesario pasar el identificador del campo a eliminar y no su valor, tal como lo indicó @leotms. Esta idea fue usada en 09330a1cce78a8f083deff100394b5dc6fa8c006. Sin embargo, en este caso la tabla en la que se guardan los campos tiene las siguientes columnas: id_catalogo | id_campo_cat | valor ([Ver schemaSIRADEx.sql](https://github.com/SergioTeranZ/Sistemas2/blob/prometheus-catalogos/SQLScripts/schemaSIRADEx.sql)). Por eso, el valor es fundamental para identificar la fila a eliminar. Esto se podría resolver añadiéndole un identificador a esta tabla.

**Comment by leotms** [comment]
Por favor verificar si este error aplica al nuevo sistema de catalogos.
